    <div>
      <a href="http://avsbq.org">avsbq.org</a> -
      <a href=".org">archive</a> -
      <a href=".org">languages</a> -
      <a href=".org">links</a> -
      <a href=".org">liturgical arts</a> -
      <a href=".org">projects</a> -
      <a href=".org">profile</a> -
      <a href=".org">tutorials</a> 
    </div>

    <div>
      <a href="http://cat-v.org/update_log">site updates</a> |
      <a href="/sitemap">site map</a>
    </div>

